language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - pip install -r requirements.txt
# command to run tests
script: "python hub/manage.py test"
notifications:
  email:
    - jarvis.travis-ci@joelbitar.se
